from yacs.config import CfgNode

# YACS overwrite these settings using YAML
_C = CfgNode()

# data augmentation parameters with albumentations library
_C.DATA_PREPROCESSING = CfgNode()
_C.DATA_PREPROCESSING.DATA_PATH = "datasets/custom_data"

_C.DATA_CREATION = CfgNode()
_C.DATA_CREATION.TRAIN_AMOUNT = 10000
_C.DATA_CREATION.TEST_AMOUNT = 2000
_C.DATA_CREATION.MIN_SIZE = 4096
_C.DATA_CREATION.AUGMENTATION = CfgNode()
_C.DATA_CREATION.AUGMENTATION.MAX_TREES = 4
_C.DATA_CREATION.AUGMENTATION.MAX_DIST = 6
_C.DATA_CREATION.AUGMENTATION.TRANSLATION_XY = 4
_C.DATA_CREATION.AUGMENTATION.TRANSLATION_Z = 0.2
_C.DATA_CREATION.AUGMENTATION.SCALE = 0.2
_C.DATA_CREATION.AUGMENTATION.XY_ROTATION = 0
_C.DATA_CREATION.AUGMENTATION.MIN_DIST_BETWEEN = 3