# run: conda env create --file environment.yml
name: treetoolml
channels:
  - "pytorch"
  - "nvidia"
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - jupyter
  - ipykernel
  - matplotlib
  - open3d
  - pandas
  - tqdm
  - numpy>=1.18.0,<2.0.0
  - yacs
  - plyfile
  - fvcore
  - tensorboard
  - python-pdal
  - scipy
  - pip
  - pip:
    - git+https://github.com/porteratzo/TreeTool.git
    - git+https://github.com/porteratzo/porteratzo3D.git
    - git+https://github.com/porteratzo/tictoc.git
    - lsq-ellipse
    - torchsummary
