#python scripts/PDE_test.py --centers --cfg configs/datasets/subconfigs/trunks.yaml --amp 1 TRAIN.BATCH_SIZE 24 VALIDATION.PATH 'datasets/custom_data/center_filtered/testing_data'
python scripts/PDE_test.py --centers --cfg configs/datasets/subconfigs/original.yaml --amp 1 TRAIN.BATCH_SIZE 24 VALIDATION.PATH 'datasets/custom_data/center_filtered/testing_data'
python scripts/PDE_test.py --centers --cfg configs/datasets/subconfigs/center_filtered.yaml --amp 1 TRAIN.BATCH_SIZE 24 VALIDATION.PATH 'datasets/custom_data/center_filtered/testing_data'
#python scripts/PDE_test.py --centers --cfg configs/experimentos_model/subconfigs/distance_out.yaml --amp 1 TRAIN.BATCH_SIZE 24 VALIDATION.PATH 'datasets/custom_data/center_filtered/testing_data'
#python scripts/PDE_test.py --centers --cfg configs/experimentos_model/subconfigs/distance_out_loss.yaml --amp 1 TRAIN.BATCH_SIZE 24 VALIDATION.PATH 'datasets/custom_data/center_filtered/testing_data'
#python scripts/PDE_test.py --centers --cfg configs/experimentos_model/subconfigs/distance_loss.yaml --amp 1 TRAIN.BATCH_SIZE 24 VALIDATION.PATH 'datasets/custom_data/center_filtered/testing_data'
