_BASE_: ../RRFSegNet.yaml

MODEL:
  OUTPUT_NODS: 4

FILES:
  DATA_WORK_FOLDER: trunks

TRAIN:
  MODEL_NAME: FILE
  BATCH_SIZE: 8
  EPOCHS: 200
  DISTANCE: 1
  DISTANCE_LOSS: 0

DATA_PREPROCESSING:
  PC_FILTER: 1
  DISTANCE_FILTER: 0.001

DATA_CREATION:
  CENTER_METHOD: 1
  TRAIN_AMOUNT: 6000
  TEST_AMOUNT: 2000
  VAL_AMOUNT: 2000
  MIN_SIZE: 4096
  AUGMENTATION:
    MAX_TREES: 12
    TRANSLATION_XY: 1.0
    TRANSLATION_Z: 0.02
    SCALE: 0.6
    XY_ROTATION: 5.0
    MIN_DIST_BETWEEN: 0.05
    DO_NORMALIZE: 1
    ZERO_FLOOR: 1