_BASE_: ../baseline.yaml

FILES:
  DATA_WORK_FOLDER: new_trunks

VALIDATION:
  PATH: 'datasets/custom_data/new_trunks/testing_data'

DATA_CREATION:
  STICK: 1
  NOISE: 0.6
  AUGMENTATION:
    TRANSLATION_XY: 1.5
    TRANSLATION_Z: 0.3
    MIN_HEIGHT: 1
    MAX_HEIGHT: 6
    XY_ROTATION: 5.0
    MIN_DIST_BETWEEN: 0.1
    DO_NORMALIZE: 1
    ZERO_FLOOR: 1

MODEL:
  SIGMOID: 0
  CLASS_SIGMOID: 1
  LAST_BATCHNORM: 1
  OUTPUT_NODS: 4

DATA_PREPROCESSING:
  DISTANCE_FILTER: 0.6

TRAIN:
  DISTANCE: 1
  DISTANCE_LOSS: 1

BENCHMARKING:
  VERTICALITY: 0.16
  CURVATURE: 0.24
  CENTER_DETECTION_ENABLE: 0
  COMBINE_STEMS: 0