_BASE_: ../baseline.yaml

FILES:
  DATA_WORK_FOLDER: trunks

TRAIN:
  MODEL_NAME: FILE
  BATCH_SIZE: 10
  EPOCHS: 100
  DISTANCE: 0
  DISTANCE_LOSS: 0

VALIDATION:
  PATH: 'datasets/custom_data/trunks/testing_data'

DATA_PREPROCESSING:
  PC_FILTER: 1
  DISTANCE_FILTER: 0.0

BENCHMARKING:
  OVERLAP: 0.2
  VOXEL_SIZE: 0.04
  WINDOW_STRIDE: 8
  XY_THRESHOLD: 80

DATA_CREATION:
  USE_CENTER_FILTERED: 1
  CENTER_METHOD: 1
  TRAIN_AMOUNT: 10000
  TEST_AMOUNT: 2000
  VAL_AMOUNT: 2000
  MIN_SIZE: 4096
  AUGMENTATION:
    MAX_TREES: 10
    TRANSLATION_XY: 3.0
    TRANSLATION_Z: 0.02
    MIN_HEIGHT: 2
    MAX_HEIGHT: 6
    XY_ROTATION: 5.0
    MIN_DIST_BETWEEN: 0.2
    DO_NORMALIZE: 1
    ZERO_FLOOR: 1